### ISSUE TITLE
Factory with name 'SimpleNet' is already present

### ISSUE THREAD

**Issue by WinniyGD** [NJUNLP/SKER#2]
Hi,

env : 
python==3.6
torch==1.6
allennlp==2.1.0

I use the command ` allennlp train config\sker.jsonnet -s tmp\ --include-package src ` trying to run your codes, but threw the following error : 

`catalyst.registry.registry.RegistryException: Factory with name 'SimpleNet' is already present
Already registered: '<class 'tests._tests_contrib_dl_callbacks.model.SimpleNet'>'
New: '<class 'tests._tests_cv_classification.model.SimpleNet'>'
`

What's the correct command to run your codes ?

**Comment by WrRan** [comment]
Thanks for your attention. Please have a look at https://github.com/WrRan/SKER.

If you have a problem, please open an issue or email me.
